### Function: Local invocation with event captured from portal

POST http://localhost:7089/runtime/webhooks/EventGrid?functionName=EventGridFunction
content-type: application/json
aeg-event-type: Notification

{
    "data": {
        "api": "PutBlob",
        "blobType": "BlockBlob",
        "clientRequestId": "87587374-4264-4e5c-875a-5d912c31465e",
        "contentLength": 2130,
        "contentOffset": null,
        "contentType": "application/octet-stream",
        "eTag": "0x8DD034721B5280E",
        "identity": null,
        "requestId": "fc9bee32-b01e-003c-122f-35a9a7000000",
        "sequencer": "0000000000000000000000000003C5ED00000000000f3e74",
        "storageDiagnostics": {
            "batchId": "737bfd88-4006-005a-002f-35e687000000"
        },
        "url": "http://127.0.0.1:10000/devstoreaccount1/webhook-payloads-accepted/LovelyLoans/QuickValuationCo/2024-04-30/2024-04-30T18:13:03UTC-e2a8e023-079c-4ce5-ac0f-2021264f92fe.json"
    },
    "dataVersion": "",
    "eventTime": "2024-11-12T18:17:38.4562975+00:00",
    "eventType": "Microsoft.Storage.BlobCreated",
    "id": "9285afe2-b01e-002c-562f-356ccf0608c2",
    "subject": "/blobServices/default/containers/webhook-payloads-accepted/blobs/LovelyLoans/QuickValuationCo/2024-11-12/2024-11-12T18:17:37UTC-73c4470b-b629-4fdf-b9ea-d9dd4332143f.json",
    "topic": "/subscriptions/37645d0d-da4b-46a8-aa99-dbefe2e1185e/resourceGroups/WebhookProxy-ClickOps/providers/Microsoft.Storage/storageAccounts/webhookstorageclickops"
}

### Function: Local invocation with event captured from portal

POST http://localhost:7089/runtime/webhooks/EventGrid?functionName=EventGridFunction
content-type: application/json
aeg-event-type: Notification

{
    "data": {
        "api": "PutBlob",
        "blobType": "BlockBlob",
        "clientRequestId": "87587374-4264-4e5c-875a-5d912c31465e",
        "contentLength": 2130,
        "contentOffset": null,
        "contentType": "application/octet-stream",
        "eTag": "0x8DD034721B5280E",
        "identity": null,
        "requestId": "fc9bee32-b01e-003c-122f-35a9a7000000",
        "sequencer": "0000000000000000000000000003C5ED00000000000f3e74",
        "storageDiagnostics": {
            "batchId": "737bfd88-4006-005a-002f-35e687000000"
        },
        "url": "https://webhookstorageclickops.blob.core.windows.net/webhook-payloads-accepted/LovelyLoans/QuickValuationCo/2024-11-12/2024-11-12T18:23:39UTC-e57ddd5d-5f47-4621-83e5-b7997766c573.json"
    },
    "dataVersion": "",
    "eventTime": "2024-11-12T18:17:38.4562975+00:00",
    "eventType": "Microsoft.Storage.BlobCreated",
    "id": "9285afe2-b01e-002c-562f-356ccf0608c2",
    "subject": "/blobServices/default/containers/webhook-payloads-accepted/blobs/LovelyLoans/QuickValuationCo/2024-11-12/2024-11-12T18:17:37UTC-73c4470b-b629-4fdf-b9ea-d9dd4332143f.json",
    "topic": "/subscriptions/37645d0d-da4b-46a8-aa99-dbefe2e1185e/resourceGroups/WebhookProxy-ClickOps/providers/Microsoft.Storage/storageAccounts/webhookstorageclickops"
}

### Function: Local invocation with single CloudEvent

POST http://localhost:7089/runtime/webhooks/EventGrid?functionName=EventGridFunction
content-type: application/json
aeg-event-type: Notification

{
    "specversion": "1.0",
    "type": "Microsoft.Storage.BlobCreated",  
    "source": "/subscriptions/{subscription-id}/resourceGroups/{resource-group}/providers/Microsoft.Storage/storageAccounts/{storage-account}",
    "id": "9aeb0fdf-c01e-0131-0922-9eb54906e209",
    "time": "2019-11-18T15:13:39.4589254Z",
    "subject": "blobServices/default/containers/{storage-container}/blobs/{new-file}",    
    "data": {
        "api": "PutBlockList",
        "clientRequestId": "4c5dd7fb-2c48-4a27-bb30-5361b5de920a",
        "requestId": "9aeb0fdf-c01e-0131-0922-9eb549000000",
        "eTag": "0x8D76C39E4407333",
        "contentType": "image/png",
        "contentLength": 30699,
        "blobType": "BlockBlob",
        "url": "https://gridtesting.blob.core.windows.net/testcontainer/{new-file}",
        "sequencer": "000000000000000000000000000099240000000000c41c18",
        "storageDiagnostics": {
            "batchId": "681fe319-3006-00a8-0022-9e7cde000000"
        }
    }
}

### Function: Local invocation with multiple EventGrid events

POST http://localhost:7089/runtime/webhooks/EventGrid?functionName=EventGridFunction
content-type: application/json
aeg-event-type: Notification

[
  {
    "topic": "/subscriptions/{subscriptionid}/resourceGroups/eg0122/providers/Microsoft.Storage/storageAccounts/egblobstore",
    "subject": "/blobServices/default/containers/{containername}/blobs/blobname.jpg",
    "eventType": "Microsoft.Storage.BlobCreated",
    "eventTime": "2018-01-23T17:02:19.6069787Z",
    "id": "{guid}",
    "data": {
      "api": "PutBlockList",
      "clientRequestId": "{guid}",
      "requestId": "{guid}",
      "eTag": "0x8D562831044DDD0",
      "contentType": "application/octet-stream",
      "contentLength": 2248,
      "blobType": "BlockBlob",
      "url": "https://egblobstore.blob.core.windows.net/{containername}/blobname.jpg",
      "sequencer": "000000000000272D000000000003D60F",
      "storageDiagnostics": {
        "batchId": "{guid}"
      }
    },
    "dataVersion": "",
    "metadataVersion": "1"
  }
]
