POST http://localhost:7089/api/handle/contract/test-v1/sender/quick-valuer/tenant/lovely-lender HTTP/1.1
content-type: application/json

{
    "userId": 12345,
    "name": "John Doe",
    "emailX": "johndoe@example.com",
    "age": 30,
    "isMember": true
}

###

