### APIM: Valid request

POST https://tenpiac-clickops-webhook-proxy-apim.azure-api.net/10piac-clickops-webhook-proxy/handle/contract/ValuationReportV1/sender/QuickValuationCo/tenant/LovelyLoans HTTP/1.1
Host: tenpiac-clickops-webhook-proxy-apim.azure-api.net
Ocp-Apim-Subscription-Key: {{ocpApimSubscriptionKey}}

{
"reportId": "VR123456789",
"date": "2024-01-17",
"propertyAddress": "123 Main St, Anytown, AT 12345",
"ownerName": "John Doe",
"estimatedValue": 750000,
"valuationMethod": "Comparative Market Analysis",
"appraiser": "Jane Smith",
"appraiserContact": "jane.smith@example.com",
"landArea": 5000,
"buildingArea": 1500
}

### APIM: Invalid request

POST https://tenpiac-clickops-webhook-proxy-apim.azure-api.net/10piac-clickops-webhook-proxy/handle/contract/ValuationReportV1/sender/QuickValuationCo/tenant/LovelyLoans HTTP/1.1
Host: tenpiac-clickops-webhook-proxy-apim.azure-api.net
Ocp-Apim-Subscription-Key: {{ocpApimSubscriptionKey}}

{
    "reportId": "VR123456789",
    "date": "2024-01-17",
    "propertyAddress": "123 Main St, Anytown, AT 12345",
    "ownerFullname": "John Doe",
    "estimatedValue": 750000,
    "valuationMethod": "Comparative Market Analysis",
    "appraiser": "Jane Smith",
    "appraiserContact": "jane.smith@example.com",
    "landArea": 5000,
    "buildingArea": 1500
}

### Function: Valid request

POST {{host}}/api/handle/contract/ValuationReportV1/sender/QuickValuationCo/tenant/LovelyLoans HTTP/1.1
content-type: application/json
x-request-id: {{$guid}}
x-functions-key: {{validateAndStoreFunctionApiKey}}

{
    "reportId": "VR123456789",
    "date": "2024-01-17",
    "propertyAddress": "123 Main St, Anytown, AT 12345",
    "ownerName": "John Doe",
    "estimatedValue": 750000,
    "valuationMethod": "Comparative Market Analysis",
    "appraiser": "Jane Smith",
    "appraiserContact": "jane.smith@example.com",
    "landArea": 5000,
    "buildingArea": 1500
}

### Function: Invalid request

POST {{host}}/api/handle/contract/ValuationReportV1/sender/QuickValuationCo/tenant/LovelyLoans HTTP/1.1
content-type: application/json
x-request-id: {{$guid}}
x-functions-key: {{validateAndStoreFunctionApiKey}}

{
    "reportId": "VR123456789",
    "date": "2024-01-17",
    "propertyAddress": "123 Main St, Anytown, AT 12345",
    "ownerFullname": "John Doe",
    "estimatedValue": 750000,
    "valuationMethod": "Comparative Market Analysis",
    "appraiser": "Jane Smith",
    "appraiserContact": "jane.smith@example.com",
    "landArea": 5000,
    "buildingArea": 1500
}

### Function: Invalid JSON

POST {{host}}/api/handle/contract/ValuationReportV1/sender/QuickValuationCo/tenant/LovelyLoans HTTP/1.1
content-type: application/json
x-request-id: {{$guid}}
x-functions-key: {{validateAndStoreFunctionApiKey}}

{
    "reportId": "VR123456789"
    "date": "2024-01-17",
    "propertyAddress": "123 Main St, Anytown, AT 12345",
    "ownerFullname": "John Doe",
    "estimatedValue": 750000,
    "valuationMethod": "Comparative Market Analysis",
    "appraiser": "Jane Smith",
    "appraiserContact": "jane.smith@example.com",
    "landArea": 5000,
    "buildingArea": 1500
}
